const PLUS_ONE_START_POS = -110;
const PLUS_ONE_FINISH_POS = -170;
const PLUS_ONE_DURATION = 300;
const PLUS_ONE_FADE_DELAY = 50;

const GAVEL_START_POS = -15;
const GAVEL_FINISH_POS = -80;
const GAVEL_UP_DURATION = 70;
const GAVEL_DOWN_DURATION = 10;

const SHOW = 1;
const HIDE = 0;
const TIMER_COUNT = 2;
const IMAGE_TRANSITION = 200;

const TIMINGS = {
  GAVEL_START_POS,
  GAVEL_FINISH_POS,
  GAVEL_UP_DURATION,
  GAVEL_DOWN_DURATION,
  PLUS_ONE_START_POS,
  PLUS_ONE_FINISH_POS,
  PLUS_ONE_DURATION,
  PLUS_ONE_FADE_DELAY,
  SHOW,
  HIDE,
  IMAGE_TRANSITION,
  TIMER_COUNT
};
export default TIMINGS